version: '3'

services:
  rabbit-consumer:
    build: .
    container_name: rabbit-consumer
    environment:
      - RABBIT_IN_HOST=rabbitmq
      - RABBIT_OUT_HOST=rabbitmq
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 200M
      restart_policy:
        condition: on-failure
        delay: 10s
    depends_on:
      - "rabbitmq"

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq-instance
    ports:
      - "8080:15672"
      - "5672:5672"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
      restart_policy:
        condition: always
        delay: 5s


